Extracted where clause out of update_all() into where()
Background:

  In Rails 4 update_all() only accept one argument, which is assignment/updation query fragment

Fixes:

  ArgumentError: wrong number of arguments (2 for 1) in task_edit_test