Return nil instead of raising an exception
Context.xml file is not being provided to the app on Jenkins and an exception `NoMethodError: undefined method 'secret_key' for nil:NilClass` is causing the build to fail.