In rails 4 integration tests inherit from ActionDispatch::IntegrationTest instead of ActionController::IntegrationTest
Fixes weird error of `NoMethodError: undefined method 'setup' for #<Class:0x1fa4af2a>`